package com.example.demo.domain.entity;

public enum AuditAction {
    TEACHER_NOTE,
    TEACHER_WARNING,
    TEACHER_PAUSE,
    TEACHER_RESUME,
    TEACHER_INVALIDATE,
    SYSTEM_DUPLICATE_IP,
    SYSTEM_IP_CHANGE,
    SYSTEM_RISK_WARNING,
    SYSTEM_ATTEMPT_PAUSE,
    SYSTEM_ATTEMPT_RESUME
}
