package com.example.demo.domain.entity;

public enum MonitoringEventType {
    ATTEMPT_START,
    DRAFT_SAVE,
    ATTEMPT_SUBMIT,
    AUTO_SUBMIT,
    NOTE,
    TEACHER_WARNING,
    TEACHER_PAUSE,
    TEACHER_RESUME,
    TEACHER_INVALIDATE,
    TAB_SWITCH,
    BLUR,
    EXIT_FULLSCREEN,
    FAST_SUBMIT,
    DUPLICATE_IP,
    COPY_PASTE,
    IDLE_TIME,
    DEVTOOLS_OPEN,
    RIGHT_CLICK,
    PRINT_SCREEN,
    RAPID_QUESTION_SWITCH,
    MULTI_MONITOR,
    HEARTBEAT_STALE,
    DEVICE_FINGERPRINT_CHANGED
}
