/**
 * Optimized Icon Component
 * Only imports icons that are actually used in the project
 * Achieves ~80% size reduction by tree-shaking unused icons
 */
// Import ONLY icons that are used in the project
// This enables tree-shaking and significantly reduces bundle size
import {
  Bell,
  BellOff,
  X,
  Check,
  CheckCircle,
  CheckCircle2,
  CheckSquare,
  ChevronLeft,
  ChevronRight,
  ChevronDown,
  ChevronUp,
  Circle,
  CircleDot,
  FileText,
  List,
  Menu,
  Home,
  User,
  Users,
  UserPlus,
  UserMinus,
  UserCheck,
  UserX,
  LogIn,
  LogOut,
  ArrowLeft,
  ArrowRight,
  ExternalLink,
  Copy,
  Clipboard,
  Edit3,
  Trash2,
  Save,
  Search,
  SearchX,
  Eye,
  EyeOff,
  AlertTriangle,
  AlertCircle,
  Info,
  HelpCircle,
  RefreshCw,
  Radio,
  Video,
  VideoOff,
  Mic,
  MicOff,
  Monitor,
  Activity,
  Pause,
  PauseCircle,
  Play,
  Ban,
  LayoutDashboard,
  BookOpen,
  Award,
  Clock,
  Timer,
  TimerOff,
  Calendar,
  CalendarDays,
  CalendarCheck2,
  Shield,
  ShieldOff,
  ShieldCheck,
  ShieldAlert,
  BarChart2,
  BarChart3,
  TrendingUp,
  TrendingDown,
  Minus,
  Mail,
  Flag,
  FlagOff,
  MessageSquare,
  Folder,
  FolderOpen,
  Image,
  Link,
  Globe,
  MapPin,
  Phone,
  Lock,
  Unlock,
  Star,
  Heart,
  ThumbsUp,
  ThumbsDown,
  Share2,
  GraduationCap,
  Library,
  Flame,
  Trophy,
  Dumbbell,
  Gamepad2,
  Film,
  Music,
  UtensilsCrossed,
  Plane,
  Car,
  Bus,
  Train,
  Wifi,
  WifiOff,
  Network,
  MoreVertical,
  MoreHorizontal,
  GripVertical,
  Filter,
  Maximize,
  Minimize,
  Zap,
  Code,
  Terminal,
  Wrench,
  PieChart,
  Type,
  Brain,
  Bookmark,
  Settings,
  DollarSign,
  CreditCard,
  Landmark,
  PiggyBank,
  Briefcase,
  HardHat,
  ShoppingCart,
  LayoutGrid,
  Key,
  Database,
  Cloud,
  CloudOff,
  Archive,
  RotateCcw,
  UserCog,
  Accessibility,
  Baby,
  Lightbulb,
  Gauge,
  Sun,
  Moon,
  Sparkles,
  ListOrdered,
  FileCheck2,
  ServerOff,
  Server,
  Presentation,
  Radar,
  Table,
  SkipForward,
  SkipBack,
  Tv,
  ArrowUpDown,
  ArrowLeftRight,
  FileWarning,
  Square,
  PlayCircle,
  StopCircle,
  CloudUpload,
  Upload,
  Download,
  Printer,
  Rss,
  Hand,
  Hash,
  CalendarClock,
  Plus,
  XCircle,
  FilePen,
  Loader2,
  Send,
  Inbox,
  Tag,
  StickyNote,
  ImageOff,
  FilterX,
  KeyRound,
  CalendarRange,
  MailPlus,
  CheckCheck,
  TextCursorInput,
  Fingerprint,
  MousePointer2,
  Layers,
  GitBranch,
  CirclePlus,
  PanelsLeftRight,
  Palette,
  BookmarkPlus,
  BookmarkCheck,
  MonitorSmartphone,
  BellRing,
} from 'lucide-vue-next'

// Icon name to component mapping - only includes icons that are used
/* eslint-disable no-dupe-keys -- repeated keys merge Material-style aliases onto the same Lucide component */
const ICON_MAP = {
  // Navigation & Layout
  dashboard: LayoutDashboard,
  quiz: FileText,
  list_alt: List,
  live_tv: Eye,
  assessment: BarChart2,
  radar: Radar,
  account_circle: User,
  home: Home,
  menu: Menu,
  close: X,
  check: Check,
  arrow_back: ArrowLeft,
  arrow_forward: ArrowRight,
  chevron_right: ChevronRight,
  chevron_left: ChevronLeft,
  expand_more: ChevronDown,
  expand_less: ChevronDown,
  arrow_drop_down: ChevronDown,

  // Actions
  edit: Edit3,
  delete: Trash2,
  add: Plus,
  remove: Minus,
  send: ExternalLink,
  download: Download,
  upload: Upload,
  print: Printer,
  save: Save,
  settings: Settings,
  search: Search,
  search_off: SearchX,
  visibility: Eye,
  visibility_off: EyeOff,
  open_in_new: ExternalLink,
  content_copy: Copy,
  content_paste: Clipboard,
  copy: Copy,

  // Status & Feedback
  check_circle: CheckCircle,
  check_circle_outline: CheckCircle,
  warning: AlertTriangle,
  error: AlertCircle,
  info: Info,
  help: HelpCircle,
  error_outline: AlertCircle,
  sync: RefreshCw,
  sync_disabled: RefreshCw,
  radio_button_checked: Radio,

  // Media & Recording
  videocam: Video,
  videocam_off: VideoOff,
  mic: Mic,
  mic_off: MicOff,
  screenshot: Monitor,
  monitor_heart: Activity,
  pause: Pause,
  pause_circle: PauseCircle,
  play_arrow: Play,
  block: Ban,

  // People & Groups
  group: Users,
  person: User,
  face: UserCheck,
  manage_accounts: Users,
  'user-plus': UserPlus,
  'users-plus': UserPlus,
  'user-minus': UserMinus,
  'alert-circle': AlertCircle,
  pencil: Edit3,
  'pencil-2': Edit3,
  'trash-2': Trash2,
  book_open: BookOpen,
  badge: Award,
  cake: Award,
  delete_sweep: Trash2,
  format_list_numbered: ListOrdered,
  all_inclusive: Sparkles,
  celebration: Sparkles,

  // Time & Schedule
  schedule: Clock,
  timer: Timer,
  timer_off: TimerOff,
  today: Calendar,
  calendar_today: Calendar,
  event: Calendar,
  event_available: CalendarCheck2,
  calendar_month: CalendarDays,

  // Security & Proctoring
  shield: Shield,
  shield_off: ShieldOff,
  security: ShieldCheck,
  verified_user: ShieldCheck,
  gpp_bad: ShieldAlert,

  // Data & Charts
  bar_chart: BarChart2,
  bar_chart_2: BarChart2,
  show_chart: TrendingUp,
  analytics: BarChart3,
  insights: TrendingUp,
  trending_up: TrendingUp,
  trending_down: TrendingDown,
  trending_flat: Minus,

  // Communication
  mail: Mail,
  notifications: Bell,
  notifications_off: BellOff,
  chat: MessageSquare,
  flag: Flag,

  // Files & Documents
  description: FileText,
  file_text: FileText,
  assignment: Clipboard,
  fact_check: CheckSquare,
  list: List,
  list_alt: List,
  feed: Rss,

  // Network & Connectivity
  wifi: Wifi,
  wifi_off: WifiOff,
  x: X,
  signal_cellular_off: WifiOff,
  router: Network,

  // UI & Interface
  more_vert: MoreVertical,
  more_horiz: MoreHorizontal,
  drag_indicator: GripVertical,
  refresh: RefreshCw,
  sort: ArrowUpDown,
  filter_list: Filter,
  fullscreen: Maximize,
  display_settings: Monitor,
  fullscreen_exit: Minimize,

  // Misc
  flash_on: Zap,
  bolt: Zap,
  code: Code,
  terminal: Terminal,
  build: Wrench,
  folder: Folder,
  folder_open: FolderOpen,
  image: Image,
  picture_as_pdf: FileText,
  pie_chart: PieChart,
  text_fields: Type,
  psychology: Brain,
  bookmark: Bookmark,
  bookmark_border: Bookmark,
  language: Globe,
  lock: Lock,
  lock_open: Unlock,
  star: Star,
  star_border: Star,
  grade: Star,
  stars: Star,
  favorite: Heart,
  favorite_border: Heart,
  thumb_up: ThumbsUp,
  thumb_down: ThumbsDown,
  share: Share2,
  link: Link,
  public: Globe,
  place: MapPin,
  contact_phone: Phone,
  email: Mail,
  phone: Phone,
  computer: Monitor,
  desktop_windows: Monitor,
  tablet: Monitor,
  smartphone: Monitor,
  mouse: Monitor,
  keyboard: Terminal,
  foggy: CloudOff,
  report: FileWarning,
  table_chart: Table,
  compare_arrows: ArrowLeftRight,
  timeline: Activity,
  domain: Globe,
  school: GraduationCap,
  book: BookOpen,
  book_open: BookOpen,
  library_books: Library,
  local_fire_department: Flame,
  workspace_premium: Award,
  emoji_events: Trophy,
  sports: Dumbbell,
  sports_esports: Gamepad2,
  movie: Film,
  music_note: Music,
  restaurants: UtensilsCrossed,
  flight: Plane,
  directions_car: Car,
  directions_bus: Bus,
  train: Train,
  local_hospital: Activity,
  science: Sparkles,
  agriculture: Sparkles,
  engineering: Wrench,
  business_center: Briefcase,
  military_tech: Shield,
  government: Sparkles,
  real_estate_agent: MapPin,
  construction: HardHat,
  shopping_cart: ShoppingCart,
  attach_money: DollarSign,
  credit_card: CreditCard,
  account_balance: Landmark,
  savings: PiggyBank,
  category: LayoutGrid,
  apps: LayoutGrid,
  vpn_key: Key,
  storage: Database,
  cloud: Cloud,
  cloud_upload: CloudUpload,
  cloud_off: CloudOff,
  backup: Archive,
  restore: RotateCcw,
  supervisor_account: UserCog,
  accessibility: Accessibility,
  pets: Baby,
  child_care: Baby,
  family_restroom: Users,
  pregnant_woman: Baby,
  self_improvement: Heart,
  spa: Sparkles,
  nightlight: Moon,
  wb_sunny: Sun,
  eco: Sparkles,
  speed: Gauge,
  skip_next: SkipForward,
  skip_previous: SkipBack,
  radio: Radio,
  live_tv: Tv,
  movie_filter: Film,
  music_video: Music,
  repeat: RefreshCw,
  repeat_one: RefreshCw,
  shuffle: RefreshCw,
  volume_up: Sparkles,
  volume_off: Sparkles,
  progressive_pause_circle: PauseCircle,
  play_circle: PlayCircle,
  stop_circle: StopCircle,

  // Custom icons
  waving_hand: Hand,
  model_training: Brain,
  calendar_month: CalendarDays,
  summarize: FileText,
  inventory_2: Archive,
  task_alt: CheckCircle2,
  class: GraduationCap,
  edit_note: Edit3,
  edit_square: FilePen,
  photo_camera: Sparkles,
  tune: Settings,
  graduation_cap: GraduationCap,
  'graduation-cap': GraduationCap,
  groups: Users,
  people: Users,
  users: Users,
  'chevron-right': ChevronRight,
  'chevron-left': ChevronLeft,
  'user-plus': UserPlus,
  'user-check': UserCheck,
  'user-x': UserX,
  'arrow_forward': ArrowRight,
  'arrow_back': ArrowLeft,
  'pending_actions': Clock,
  'account_circle': User,
  'upload_file': Upload,
  'cloud_upload': CloudUpload,
  'analytics': BarChart3,
  'schedule': Clock,
  'hourglass_top': Timer,
  'download': Download,
  'star': Star,
  'grade': Star,
  'waving_hand': Hand,
  'bar_chart_2': BarChart2,
  'hash': Hash,
  'login': LogIn,
  'logout': LogOut,
  'alert-triangle': AlertTriangle,
  alert_circle: AlertCircle,
  'check-circle': CheckCircle,
  'layout_dashboard': LayoutDashboard,
  'clipboard_list': Clipboard,
  'message_circle': MessageSquare,
  'file_check_2': FileCheck2,
  'server_off': ServerOff,
  'help_circle': HelpCircle,
  'log_out': LogOut,
  'shield_check': ShieldCheck,
  'co_present': Presentation,
  'activity': Activity,
  'server': Server,
  'refresh': RefreshCw,
  'x': X,
  'users': Users,
  'trending_up': TrendingUp,
  'trending_down': TrendingDown,
  'presentation': Presentation,
  'pending': Clock,
  'file_text': FileText,
  'plus': Plus,

  // Exam specific
  rocket_launch: Zap,
  tips_and_updates: Lightbulb,
  lightbulb: Lightbulb,
  support_agent: Users,
  event_busy: Calendar,
  event_note: Calendar,
  verified_user: ShieldCheck,
  inventory_2: Archive,
  cast: Tv,
  do_not_disturb_on: Ban,
  delete_forever: Trash2,
  hourglass_empty: Timer,
  hourglass_full: Timer,
  hourglass_top: Timer,
  done_all: CheckCheck,
  fullscreen: Maximize,
  info: Info,
  done: Check,
  cloud_off: CloudOff,
  bookmark: Bookmark,
  check_circle_outline: CheckCircle,

  // Additional icons
  expand_more: ChevronDown,
  expand_less: ChevronUp,
  history: CalendarClock,
  monitoring: Activity,
  publish: Upload,
  unpublished: EyeOff,
  unarchive: RotateCcw,
  call_split: GitBranch,
  history_edu: BookOpen,
  leaderboard: Trophy,
  trending: TrendingUp,
  trending_flat: Minus,
  cancel: XCircle,
  check_box: CheckSquare,
  check_box_outline_blank: Square,
  radio_button_unchecked: Circle,
  notifications_off: BellOff,

  // Extra keys used in templates / configs
  today: Calendar,
  arrow_drop_down: ChevronDown,
  open_in_new: ExternalLink,
  rotate_ccw: RotateCcw,
  image_off: ImageOff,
  text_cursor_input: TextCursorInput,
  signal_wifi_connected_no_internet_4: WifiOff,
  table: Table,
  date_range: CalendarRange,
  notes: StickyNote,
  key_round: KeyRound,
  outgoing_mail: MailPlus,
  person_add: UserPlus,
  filter_alt_off: FilterX,
  tag: Tag,
  progress_activity: Loader2,
  loader_2: Loader2,
  send: Send,
  satellite_alt: Radar,
  vertical_distribute: PanelsLeftRight,
  palette: Palette,
  bookmark_add: BookmarkPlus,
  bookmark_added: BookmarkCheck,
  key: Key,
  file: FileText,
  devices: MonitorSmartphone,

  // Missing name variants used in teacher UI
  wifi: Wifi,
  'wifi-off': WifiOff,
  'bell-ring': BellRing,
  bell_ring: BellRing,
  layout: LayoutGrid,
  'refresh-cw': RefreshCw,
  refresh_cw: RefreshCw,
  'check-square': CheckSquare,
  check_square: CheckSquare,
  minimize: Minimize,
  maximize: Maximize,
  ban: Ban,
  send: Send,
  square: Square,
  play: Play,
  tab: Layers,
  layers: Layers,
  'shield-alert': ShieldAlert,
  shield_alert: ShieldAlert,
  'mouse-pointer-2': MousePointer2,
  mouse_pointer_2: MousePointer2,
  'bar-chart-2': BarChart2,
  bar_chart_2: BarChart2,
  'circle-dot': CircleDot,
  circle_dot: CircleDot,

  // New icons for monitoring
  flag_off: FlagOff,
  'flag-off': FlagOff,
  user_search: User,

  // Proctoring violation icon names (getViolationIcon)
  mouse_right_button: MousePointer2,
  flip_to_front: Layers,
  sync_problem: AlertTriangle,
  person_off: UserX,
  record_voice_over: Mic,
  hub: Network,
  group_work: Users,
  fingerprint: Fingerprint,

  add_circle: CirclePlus,
  fiber_new: Sparkles,
  history_toggle_off: CalendarClock,
  password: Lock,

  // Names used in teacher UI (avoid default Circle fallback)
  preview: Eye,
  assignment_add: CirclePlus,
  menu_book: BookOpen,
  checklist: ListOrdered,

  // Explicit kebab-case mappings (faster than fallback resolver)
  'play-circle': PlayCircle,
  'pause-circle': PauseCircle,
  'stop-circle': StopCircle,
  'x-circle': XCircle,
  'help-circle': HelpCircle,
  'arrow-left': ArrowLeft,
  'arrow-right': ArrowRight,
  'eye-off': EyeOff,
  'video-off': VideoOff,
  'mic-off': MicOff,
  'cloud-off': CloudOff,
  'shield-check': ShieldCheck,
  'shield-off': ShieldOff,
  'file-text': FileText,
  'file-warning': FileWarning,
  'log-in': LogIn,
  'log-out': LogOut,
  'more-vertical': MoreVertical,
  'more-horizontal': MoreHorizontal,
  'grip-vertical': GripVertical,
  'rotate-ccw': RotateCcw,
  'panel-left-right': PanelsLeftRight,
  'sticky-note': StickyNote,
  'image-off': ImageOff,
  'filter-x': FilterX,
  'key-round': KeyRound,
  'mail-plus': MailPlus,
  'check-check': CheckCheck,
  'text-cursor-input': TextCursorInput,
  'monitor-smartphone': MonitorSmartphone,
  'bookmark-plus': BookmarkPlus,
  'bookmark-check': BookmarkCheck,
  'calendar-clock': CalendarClock,
  'calendar-days': CalendarDays,
  'calendar-range': CalendarRange,
  'calendar-check-2': CalendarCheck2,
  'check-circle-2': CheckCircle2,
  'file-pen': FilePen,
  'sparkles': Sparkles,
  'piggy-bank': PiggyBank,
  'graduation-cap': GraduationCap,
  'shopping-cart': ShoppingCart,
  'dollar-sign': DollarSign,
  'credit-card': CreditCard,
  'thumbs-up': ThumbsUp,
  'thumbs-down': ThumbsDown,
  'map-pin': MapPin,
  'message-square': MessageSquare,
  'folder-open': FolderOpen,
  'pie-chart': PieChart,
  'hard-hat': HardHat,
  'user-cog': UserCog,
  'circle-plus': CirclePlus,
  'list-ordered': ListOrdered,
  'file-check-2': FileCheck2,
  'server-off': ServerOff,
  'mouse-pointer-2': MousePointer2,
  'shield-alert': ShieldAlert,
  'bar-chart-3': BarChart3,
  'cloud-upload': CloudUpload,
  'skip-forward': SkipForward,
  'skip-back': SkipBack,
  'arrow-up-down': ArrowUpDown,
  'arrow-left-right': ArrowLeftRight,
  'circle-dot': CircleDot,
  'check-square': CheckSquare,
  'bell-ring': BellRing,
  'bell-off': BellOff,
  'wifi-off': WifiOff,
  'refresh-cw': RefreshCw,
  'bar-chart-2': BarChart2,
  'check-circle': CheckCircle,
  'alert-circle': AlertCircle,
  'alert-triangle': AlertTriangle,
  'trending-up': TrendingUp,
  'trending-down': TrendingDown,
  'layout-grid': LayoutGrid,
  'loader-2': Loader2,
  'satellite-alt': Radar,

  // Common semantic aliases used by realtime/connection states
  'connecting': Loader2,
  'live': Radio,
  'broadcast': Radar,
  'antenna': Radio,
  loader: Loader2,
  spinner: Loader2,
  signal: Wifi,
  power: Zap,
  inbox: Inbox,
  fingerprint: Fingerprint,
}

// Cache for resolved icons
const iconCache = new Map()

// Default icon fallback
const DEFAULT_ICON = Circle

export const resolveIcon = (name) => {
  if (name == null || name === '') return DEFAULT_ICON

  const raw = String(name).trim()
  if (!raw) return DEFAULT_ICON

  if (iconCache.has(raw)) {
    return iconCache.get(raw)
  }

  const underscored = raw.replace(/-/g, '_')
  const candidates = [
    raw,
    underscored,
    underscored.toLowerCase(),
    raw.replace(/_/g, ''),
    raw.replace(/_/g, '').toLowerCase()
  ]

  let icon
  for (const key of candidates) {
    if (!key) continue
    icon = ICON_MAP[key]
    if (icon) break
  }

  const resolved = icon || DEFAULT_ICON
  iconCache.set(raw, resolved)
  return resolved
}

